deals/urls.py
from django.urls import path

from .views import Home, TaskAddSuccess, TaskDetail, TaskList

app_name = 'deals'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('task/', TaskList.as_view(), name='task_list'),
    path('task/<slug:slug>/', TaskDetail.as_view(), name='task_detail'),
    path('added/', TaskAddSuccess.as_view(), name='task_added'),
]

static_pages/urls.py
from django.urls import path

from .views import About

app_name = 'static_pages'

urlpatterns = [
    path('about/', About.as_view(), name='about'),
]

todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('deals.urls', namespace='deals')),
    path('page/', include('static_pages.urls', namespace='static_pages')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

deals/models.py
from django.db import models
# pip3 install pytils не забыть установить!
from pytils.translit import slugify


class Task(models.Model):
    title = models.CharField(
        'Заголовок',
        default='Значение по-умолчанию',
        max_length=100,
        help_text='Дайте короткое название задаче'
    )
    text = models.TextField(
        'Текст',
        help_text='Опишите суть задачи'
    )
    slug = models.SlugField(
        'Адрес для страницы с задачей',
        max_length=100,
        unique=True,
        blank=True,
        help_text=('Укажите адрес для страницы задачи. Используйте только '
                   'латиницу, цифры, дефисы и знаки подчёркивания')
    )
    image = models.ImageField(
        'Картинка',
        upload_to='tasks/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    def __str__(self):
        return self.title

    # Расширение встроенного метода save(): если поле slug не заполнено -
    # транслитерировать в латиницу содержимое поля title и
    # обрезать до ста знаков
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)

deals/forms.py
from django import forms
from django.core.exceptions import ValidationError
from pytils.translit import slugify

from .models import Task


class TaskCreateForm(forms.ModelForm):
    """Форма для создания задания."""
    class Meta:
        model = Task
        # Магия Джанго: через '__all__' создаётся форма из всех полей модели
        # labels и help_texts берутся из verbose_name и help_text
        fields = '__all__'

    # Валидация поля slug
    def clean_slug(self):
        """Обрабатывает случай, если slug не уникален."""
        cleaned_data = super().clean()
        slug = cleaned_data['slug']
        if not slug:
            title = cleaned_data['slug']
            slug = slugify(title)[:100]
        if Task.objects.filter(slug=slug).exists():
            raise ValidationError(f'Адрес "{slug}" уже существует, '
                                  'придумайте уникальное значение')
        return slug

deals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView

from .forms import TaskCreateForm
from .models import Task


class Home(CreateView):
    """Форма добавления задания."""
    template_name = 'deals/home.html'
    form_class = TaskCreateForm
    success_url = reverse_lazy('deals:task_added')


class TaskList(LoginRequiredMixin, ListView):
    """Список всех доступных заданий."""
    login_url = '/admin/login/'
    model = Task
    template_name = 'deals/task_list.html'



class TaskDetail(LoginRequiredMixin, DetailView):
    """Задание подробно."""
    login_url = '/admin/login/'
    model = Task
    template_name = 'deals/task_detail.html'


class TaskAddSuccess(TemplateView):
    """Задание успешно добавлено."""
    template_name = 'deals/added.html'

static_pages/views.py
from django.views.generic.base import TemplateView


class About(TemplateView):
    template_name = 'static_pages/about.html'

templates/deals/added.html
<html>
  <body>
    <h1>Задача успешно добавлена</h1>
    <a href="{% url 'deals:home' %}">На главную</a>
  </body>
</html>

templates/deals/home.html
<html>
  <body>
    <h1>Домашняя страница</h1>
    <ul>
      <li>
        <a href="{% url 'static_pages:about' %}">О проекте</a>
      </li>
      <li>
        <a href="{% url 'deals:task_list' %}">Список задач</a>
      </li>
    </ul>
    <h2>Добавить задачу</h2>
    <!-- enctype определяет способ кодирования данных формы
    при их отправке на сервер.
    Обычно устанавливать значение атрибута enctype не требуется,
    данные вполне правильно понимаются на стороне сервера.
    Однако если используется поле для отправки файла (input type="file"),
    следует определить атрибут enctype как multipart/form-data. -->
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Сохранить">
  </form>
  </body>
</html>

templates/deals/task_detail.html
<html>
  <body>
    <h1>Детализация задачи ID: {{ task.id }}</h1>
    <ul>
      <li>
        <a href="{% url 'deals:home' %}">На главную</a>
      </li>
      <li>
        <a href="{% url 'deals:task_list' %}">В список задач</a>
      </li>
    </ul>
    <h2>{{ task.title }}</h2>
    <p>{{ task.text }}</p>
    {% if task.image %}
      <img src="{{ task.image.url }}">
    {% endif %}

  </body>
</html>

templates/deals/task_list.html
<html>
  <body>
    <h1>Список задач</h1>
    <ul>
      {% for task in object_list %}
        <li>
          <a href="{% url 'deals:task_detail' task.slug %}">{{ task.title }}</a>
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'deals:home' %}">На главную</a>
  </body>
</html>

templates/static_pages/about.html
<html>
  <body>
    <h1>О проекте</h1>
    <p>
      Проект Todo поможет вам не забыть о самом важном
    </p>
    <a href="{% url 'deals:home' %}">На главную</a>
  </body>
</html>